### ISSUE TITLE
subscriptionsClient.subscribe is not a function

### ISSUE THREAD

**Issue by sebastienvermeille** [npalm/graphql-java-demo#14]
Hi,
I just runned the docker image to test it (I try to achieve subscription in real time working with java (what your project does! :) )

But I get an error when I execute the following graphql query:

`
subscription {
  comments {
    comment
    author
    talk {
      title
    }
    createdOn
  }
}
`

error received:
`
subscriptionsClient.subscribe is not a function
`

In the browser console I get a websocket error:
`
WebSocket connection to 'ws://localhost:8080/subscriptions' failed: Error during WebSocket handshake: Unexpected response code: 404
`

Do you have any solution ?

Note: after investigation it seems it's related to graphiQl:
https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/220

**Comment by npalm** [comment]
@sebastienvermeille thanks for creating the issue, I will have a look in the next week.

**Comment by npalm** [comment]
@sebastienvermeille did you got it working? I

**Comment by npalm** [comment]
Bit late, thks for the PR @sebastienvermeille
